name: Node.js Publish

on:
    push:
        branches:
            - 'release/**'
    page_build:
    release:
        types:
            - published

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: pnpm/action-setup@v4
                with:
                    version: latest
            -   uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: 'pnpm'
            -   run: pnpm install --frozen-lockfile
            -   run: pnpm run lint
            -   run: pnpm run test
            -   name: SonarCloud Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: pnpm/action-setup@v4
                with:
                    version: latest
            -   uses: actions/setup-node@v4
                with:
                    node-version: 22
                    registry-url: https://registry.npmjs.org/
                    cache: 'pnpm'
            -   run: pnpm install --frozen-lockfile
            -   run: npm publish --access public
                env:
                    NODE_AUTH_TOKEN: ${{secrets.npm_token}}
