name: "Node.js Update changelog"

on:
    push:
        branches:
            - 'master'

jobs:
    update-changelog:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v7
            -   name: Update Release Draft
                uses: release-drafter/release-drafter@v7
                env:
                    GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
