name: Node.js Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v7
            -   uses: pnpm/action-setup@v6
                with:
                    version: latest
            -   uses: actions/setup-node@v6
                with:
                    node-version: 22
                    cache: 'pnpm'
            -   run: pnpm install --frozen-lockfile
            -   run: pnpm run lint
            -   run: pnpm run test
            -   name: SonarCloud Scan
                uses: SonarSource/sonarqube-scan-action@v8
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    SONAR_HOST_URL: https://sonarcloud.io
            -   name: Create Release
                uses: softprops/action-gh-release@v3
                with:
                    tag_name: ${{ github.ref_name }}
                    name: Release ${{ github.ref_name }}
                    generate_release_notes: true
                    draft: false
                    prerelease: false
                env:
                    GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
