name: Node.js Release

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: pnpm/action-setup@v4
                with:
                    version: latest
            -   uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: 'pnpm'
            -   run: pnpm install --frozen-lockfile
            -   run: pnpm run lint
            -   run: pnpm run test
            -   name: SonarCloud Scan
                uses: SonarSource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # Needed to get PR information, if any
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            -   name: Changelog
                uses: scottbrenner/generate-changelog-action@master
                id: Changelog
            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: Release ${{ github.ref }}
                    body: |
                        # Change Log
                        
                        ## ${{ github.ref }} (May 27, 2019)
                        
                        - Automatic generation release.
                    draft: false
                    prerelease: false
