name: Node.js Release Drafter

on:
    push:
        branches:
            - 'feature/**'
            - 'bugfix/**'
            - 'hotfix/**'
            - 'develop'

jobs:
    update_release_draft:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            -   uses: release-drafter/release-drafter@v7
                env:
                    GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
