name: "Node.js Update changelog"
on:
  push:
    branches:
      - 'release/**'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - name: Update changelog
        run: |
          export GREN_GITHUB_TOKEN=${{ secrets.GIT_TOKEN }}
          ./node_modules/.bin/gren changelog --override
      - name: Get base branch
        id: vars
        run: |
          base_ref=${{ github.head_ref || github.ref }}
          echo ::set-output name=base_branch::${base_ref#refs/*/}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: Update changelog
          delete-branch: true
          title: Update Changelog
          body: |
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            - Update changelog to reflect release changes

            [1]: https://github.com/sercheo87/convert-postman-jmeter
          branch: update-changelog
          base: master
          labels: automated pr
          assignees: sercheo87
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
